services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: forja_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    networks:
      - forja_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: forja_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - forja_net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    container_name: forja_schema_registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - forja_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: forja_kafka_ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: forja-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    networks:
      - forja_net

  postgres:
    image: postgres:15
    container_name: forja_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: snrt_readonly
      POSTGRES_PASSWORD: 6AOd3Dm2
      POSTGRES_DB: snrt_stats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forja_net

  minio:
    image: minio/minio:latest
    container_name: forja_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - forja_net

  spark-master:
    build: ./spark_docker
    container_name: forja_spark_master
    restart: unless-stopped
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark_jobs:/opt/spark_jobs
    networks:
      - forja_net

  spark-worker:
    build: ./spark_docker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    restart: unless-stopped
    volumes:
      - ./spark_jobs:/opt/spark_jobs
    networks:
      - forja_net

  ga4-producer:
    build: ./producers
    container_name: ga4-producer
    depends_on:
      - kafka
    environment:
      GA4_PROPERTY_ID: ${GA4_PROPERTY_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: ga4.events
      PRODUCER_INTERVAL: "300"
    volumes:
      - ./producers/credentials.json:/app/credentials.json
    networks:
      - forja_net
    restart: unless-stopped


  spark-worker-silver:
    build: ./spark_docker
    container_name: forja_spark_worker_silver
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    restart: unless-stopped
    volumes:
      - ./spark_jobs:/opt/spark_jobs
    networks:
      - forja_net

  bronze-consumer:

    build: ./spark_docker

    container_name: forja_bronze_consumer

    restart: unless-stopped

    depends_on:

      - spark-master

      - kafka

    environment:

      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

      MINIO_ENDPOINT: http://minio:9000

      MINIO_ROOT_USER: ${MINIO_ROOT_USER}

      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: >

      spark-submit

      --master spark://spark-master:7077

      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0

      --jars /opt/spark_jobs/jars/kafka-clients-3.4.1.jar,/opt/spark_jobs/jars/aws-java-sdk-bundle-1.12.262.jar

      /opt/spark_jobs/bronze_consumer.py

    volumes:

      - ./spark_jobs:/opt/spark_jobs

      - ./offsets:/tmp

    networks:

      - forja_net

networks:
  forja_net:
    external: true

volumes:
  postgres_data:
  minio_data:
  kafka_data:
  zookeeper_data:
  zookeeper_logs:
